/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package friendlytemplate.utilities;

import friendlytemplate.list.LinkedList;

/**
 * Another helper class.
 */
class JoinUtils {
    /**
     * another helper method.
     *
     * @param source data
     * @return value
     */
    public static String join(LinkedList source) {
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < source.size(); ++i) {
            if (result.length() > 0) {
                result.append(" ");
            }
            result.append(source.get(i));
        }

        return result.toString();
    }
}
