/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package friendlytemplate.utilities;

/** Sample utility class. */
public class StringUtils {
    private StringUtils() {}

    /** sample library function that just returns 'Hello World' */
    public static String getMessage() {
        return "Hello World";
    }
}
