/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("friendlytemplate.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))

    // Command line interface library
    implementation("info.picocli:picocli:4.6.3")

}

application {
    // Define the main class for the application.
    mainClass.set("friendlytemplate.app.App")
}
